---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{vcenter_name}}"
      username: "{{vcenter_username}}"
      password: "{{vcenter_password}}"
      validate_certs: False
      name: "{{ vm_name }}"
      template: win2019
      datacenter: "DC1"
      state: poweredon
      folder: DC1/vm
      cluster: "Lab"
      wait_for_ip_address: yes
